---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vote-api-trigger-template
spec:
  params:
    - name: git-revision
      description: The git revision
      default: master
    - name: git-url
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-and-deploy-vote-api-app-
        labels:
          tekton.dev/pipeline: build-and-deploy-vote-api-app-deploy
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: build-and-deploy
        params:
          - name: git-url
            value: "$(tt.params.git-url)"
          - name: git-revision
            value: "$(tt.params.git-revision)"
          - name: image
            value: image-registry.openshift-image-registry.svc:5000/vote-app/pipelines-vote-api
          - name: deployment-name
            value: "pipelines-vote-api"
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: source-pvc
---
apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: vote-ui-trigger-template
spec:
  params:
    - name: git-revision
      description: The git revision
      default: master
    - name: git-url
      description: The git repository url
  resourcetemplates:
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        generateName: build-and-deploy-vote-ui-app-
        labels:
          tekton.dev/pipeline: build-and-deploy-vote-ui-app-deploy
      spec:
        serviceAccountName: pipeline
        pipelineRef:
          name: build-and-deploy
        params:
          - name: git-url
            value: "$(tt.params.git-url)"
          - name: git-revision
            value: "$(tt.params.git-revision)"
          - name: image
            value: image-registry.openshift-image-registry.svc:5000/vote-app/pipelines-vote-ui
          - name: deployment-name
            value: "pipelines-vote-ui"
        workspaces:
          - name: shared-workspace
            persistentVolumeClaim:
              claimName: source-pvc
